/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     DIGITS = 8
     BASE = 16
*/
module multi_base_ctr_6 (
    input clk,
    input rst,
    input inc,
    output reg [39:0] digits
  );
  
  localparam DIGITS = 4'h8;
  localparam BASE = 5'h10;
  
  
  wire [(4'h8+0)-1:0] M_dctr_ovf;
  wire [(4'h8+0)*5-1:0] M_dctr_value;
  reg [(4'h8+0)-1:0] M_dctr_inc;
  
  genvar GEN_dctr0;
  generate
  for (GEN_dctr0=0;GEN_dctr0<4'h8;GEN_dctr0=GEN_dctr0+1) begin: dctr_gen_0
    base_ctr_11 dctr (
      .clk(clk),
      .rst(rst),
      .inc(M_dctr_inc[GEN_dctr0*(1)+(1)-1-:(1)]),
      .ovf(M_dctr_ovf[GEN_dctr0*(1)+(1)-1-:(1)]),
      .value(M_dctr_value[GEN_dctr0*(3'h5)+(3'h5)-1-:(3'h5)])
    );
  end
  endgenerate
  
  always @* begin
    M_dctr_inc[0+0-:1] = inc;
    digits = M_dctr_value;
    M_dctr_inc[1+6-:7] = M_dctr_ovf[0+6-:7];
  end
endmodule
