/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     DIGITS = 8
     DIV = 1
*/
module multi_seven_seg_5 (
    input clk,
    input rst,
    input [39:0] values,
    output reg [6:0] seg,
    output reg [7:0] sel
  );
  
  localparam DIGITS = 4'h8;
  localparam DIV = 1'h1;
  
  
  localparam DIGIT_BITS = 2'h3;
  
  wire [3-1:0] M_ctr_value;
  counter_9 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  
  wire [7-1:0] M_seg_dec_segs;
  reg [5-1:0] M_seg_dec_char;
  seven_seg_10 seg_dec (
    .char(M_seg_dec_char),
    .segs(M_seg_dec_segs)
  );
  
  always @* begin
    M_seg_dec_char = values[(M_ctr_value)*5+4-:5];
    seg = M_seg_dec_segs;
    sel = M_ctr_value;
  end
endmodule
