/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_10 (
    input [4:0] char,
    output reg [6:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      1'h0: begin
        segs = 8'h7e;
      end
      1'h1: begin
        segs = 8'h30;
      end
      2'h2: begin
        segs = 8'h6d;
      end
      2'h3: begin
        segs = 8'h79;
      end
      3'h4: begin
        segs = 8'h33;
      end
      3'h5: begin
        segs = 8'h5b;
      end
      3'h6: begin
        segs = 8'h5f;
      end
      3'h7: begin
        segs = 8'h70;
      end
      4'h8: begin
        segs = 8'h7f;
      end
      4'h9: begin
        segs = 8'h7b;
      end
      4'ha: begin
        segs = 8'h77;
      end
      4'hb: begin
        segs = 8'h1f;
      end
      4'hc: begin
        segs = 8'h4e;
      end
      4'hd: begin
        segs = 8'h3d;
      end
      4'he: begin
        segs = 8'h4f;
      end
      4'hf: begin
        segs = 8'h47;
      end
      5'h10: begin
        segs = 8'h1d;
      end
      5'h11: begin
        segs = 8'h05;
      end
      5'h12: begin
        segs = 8'h40;
      end
      default: begin
        segs = 7'h00;
      end
    endcase
  end
endmodule
